// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHw6aN94oj-ci1sj3eBXlLzZgnh-NRbYw',
    appId: '1:1091266407109:web:be41c9d58f4028d1d79eac',
    messagingSenderId: '1091266407109',
    projectId: 'ecommerce-65e31',
    authDomain: 'ecommerce-65e31.firebaseapp.com',
    storageBucket: 'ecommerce-65e31.appspot.com',
    measurementId: 'G-140KYMJV41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_qIqwIsFNL1Fu0HL09uXNL2l17ABTFX4',
    appId: '1:1091266407109:android:dd0c268af104a29dd79eac',
    messagingSenderId: '1091266407109',
    projectId: 'ecommerce-65e31',
    storageBucket: 'ecommerce-65e31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrEvzny8CkzkdzfOhZ_trxWFDYOjngST0',
    appId: '1:1091266407109:ios:cd2d0f58d2b8c511d79eac',
    messagingSenderId: '1091266407109',
    projectId: 'ecommerce-65e31',
    storageBucket: 'ecommerce-65e31.appspot.com',
    androidClientId: '1091266407109-8v3dumuhjtjtorrcp73q140vo07jorhp.apps.googleusercontent.com',
    iosClientId: '1091266407109-842db3175qh89f8c5u8m20k824impupm.apps.googleusercontent.com',
    iosBundleId: 'com.example.septra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrEvzny8CkzkdzfOhZ_trxWFDYOjngST0',
    appId: '1:1091266407109:ios:cd2d0f58d2b8c511d79eac',
    messagingSenderId: '1091266407109',
    projectId: 'ecommerce-65e31',
    storageBucket: 'ecommerce-65e31.appspot.com',
    androidClientId: '1091266407109-8v3dumuhjtjtorrcp73q140vo07jorhp.apps.googleusercontent.com',
    iosClientId: '1091266407109-842db3175qh89f8c5u8m20k824impupm.apps.googleusercontent.com',
    iosBundleId: 'com.example.septra',
  );
}
